export const goodsOptions = [
  {
    value: '1',
    label: '1',
    type: 'option',
    info: [
      'Chemicals used in industry, science and photography, as well as in agriculture, horticulture and forestry',
      'Unprocessed artificial resins, unprocessed plastics',
      'Manures',
      'Fire extinguishing compositions',
      'Tempering and soldering preparations',
      'Chemical substances for preserving foodstuffs',
      'Tanning substances',
      'Adhesives used in industry',
    ],
  },
  {
    value: '2',
    label: '2',
    type: 'option',
    info: [
      'Paints, varnishes, lacquers',
      'Preservatives against rust and against deterioration of wood',
      'Colorants',
      'Mordants',
      'Raw natural resins',
      'Metals in foil and powder form for use in painting, decorating, printing and art',
    ],
  },
  {
    value: '3',
    label: '3',
    type: 'option',
    info: [
      'Bleaching preparations and other substances for laundry use',
      'Cleaning, polishing, scouring and abrasive preparations',
      'Non-medicated soaps',
      'Perfumery, essential oils, non-medicated cosmetics, non-medicated hair lotions',
      'Non-medicated dentifrices',
    ],
  },
  {
    value: '4',
    label: '4',
    type: 'option',
    info: [
      'Industrial oils and greases',
      'Lubricants',
      'Dust absorbing, wetting and binding compositions',
      'Fuels [including motor spirit] and illuminants',
      'Candles and wicks for lighting',
    ],
  },
  {
    value: '5',
    label: '5',
    type: 'option',
    info: [
      'Pharmaceuticals, medical and veterinary preparations',
      'Sanitary preparations for medical purposes',
      'Dietetic food and substances adapted for medical or veterinary use, food for babies',
      'Dietary supplements for humans and animals',
      'Plasters, materials for dressings',
      'Material for stopping teeth, dental wax',
      'Disinfectants',
      'Preparations for destroying vermin',
      'Fungicides, herbicides',
    ],
  },
  {
    value: '6',
    label: '6',
    type: 'option',
    info: [
      'Common metals and their alloys, ores',
      'Metal materials for building and construction',
      'Transportable buildings of metal',
      'Non-electric cables and wires of common metal',
      'Small items of metal hardware',
      'Safes',
      'Metal containers for storage or transport',
    ],
  },
  {
    value: '7',
    label: '7',
    type: 'option',
    info: [
      'Machines and machine tools',
      'Motors and engines [except for land vehicles]',
      'Machine coupling and transmission components [except for land vehicles]',
      'Agricultural implements other than hand-operated',
      'Incubators for eggs',
      'Automatic vending machines',
    ],
  },
  {
    value: '8',
    label: '8',
    type: 'option',
    info: [
      'Hand tools and implements [hand-operated]',
      'Cutlery',
      'Side arms',
      'Razors',
    ],
  },
  {
    value: '9',
    label: '9',
    type: 'option',
    info: [
      'Scientific, nautical, surveying, photographic, cinematographic, optical, weighing, measuring, signalling, checking [supervision], life-saving and teaching apparatus and instruments',
      'Apparatus and instruments for conducting, switching, transforming, accumulating, regulating or controlling electricity',
      'Apparatus for recording, transmission or reproduction of sound or images',
      'Magnetic data carriers, recording discs',
      'Compact discs, dvds and other digital recording media',
      'Mechanisms for coin-operated apparatus',
      'Cash registers, calculating machines, data processing equipment, computers',
      'Computer software',
      'Fire-extinguishing apparatus',
    ],
  },
  {
    value: '10',
    label: '10',
    type: 'option',
    info: [
      'Surgical, medical, dental and veterinary apparatus and instruments',
      'Artificial limbs, eyes and teeth',
      'Orthopaedic articles',
      'Suture materials',
      'Therapeutic and assistive devices adapted for the disabled',
      'Massage apparatus',
      'Apparatus, devices and articles for nursing infants',
      'Sexual activity apparatus, devices and articles',
    ],
  },
  {
    value: '11',
    label: '11',
    type: 'option',
    info: [
      'Apparatus for lighting, heating, steam generating, cooking, refrigerating, drying, ventilating, water supply and sanitary purposes',
    ],
  },
  {
    value: '12',
    label: '12',
    type: 'option',
    info: ['Vehicles', 'Apparatus for locomotion by land, air or water'],
  },
  {
    value: '13',
    label: '13',
    type: 'option',
    info: ['Firearms', 'Ammunition and projectiles', 'Explosives', 'Fireworks'],
  },
  {
    value: '14',
    label: '14',
    type: 'option',
    info: [
      'Precious metals and their alloys',
      'Jewellery, precious and semi-precious stones',
      'Horological and chronometric instruments',
    ],
  },
  {
    value: '15',
    label: '15',
    type: 'option',
    info: ['Musical instruments'],
  },
  {
    value: '16',
    label: '16',
    type: 'option',
    info: [
      'Paper and cardboard',
      'Printed matter',
      'Bookbinding material',
      'Photographs',
      'Stationery and office requisites, except furniture',
      'Adhesives for stationery or household purposes',
      'Artists’ and drawing materials',
      'Paintbrushes',
      'Instructional and teaching materials',
      'Plastic sheets, films and bags for wrapping and packaging',
      'Printers’ type, printing blocks',
    ],
  },
  {
    value: '17',
    label: '17',
    type: 'option',
    info: [
      'Unprocessed and semi-processed rubber, gutta-percha, gum, asbestos, mica and substitutes for all these materials',
      'Plastics and resins in extruded form for use in manufacture',
      'Packing, stopping and insulating materials',
      'Flexible pipes, tubes and hoses, not of metal',
    ],
  },
  {
    value: '18',
    label: '18',
    type: 'option',
    info: [
      'Leather and imitations of leather',
      'Animal skins and hides',
      'Luggage and carrying bags',
      'Umbrellas and parasols',
      'Walking sticks',
      'Whips, harness and saddlery',
      'Collars, leashes and clothing for animals',
    ],
  },
  {
    value: '19',
    label: '19',
    type: 'option',
    info: [
      'Building materials [non-metallic]',
      'Non-metallic rigid pipes for building',
      'Asphalt, pitch and bitumen',
      'Non-metallic transportable buildings',
      'Monuments, not of metal',
    ],
  },
  {
    value: '20',
    label: '20',
    type: 'option',
    info: [
      'Furniture, mirrors, picture frames',
      'Unworked or semi-worked bone, horn, whalebone or mother-of-pearl',
      'Shells',
      'Meerschaum',
      'Yellow amber',
      'Containers, not of metal, for storage or transport',
    ],
  },
  {
    value: '21',
    label: '21',
    type: 'option',
    info: [
      'Household or kitchen utensils and containers',
      'Combs and sponges',
      'Brushes [except paintbrushes]',
      'Brush-making materials',
      'Articles for cleaning purposes',
      'Unworked or semi-worked glass, except building glass',
      'Glassware, porcelain and earthenware',
    ],
  },
  {
    value: '22',
    label: '22',
    type: 'option',
    info: [
      'Ropes and string',
      'Padding, cushioning and stuffing materials, except of paper, cardboard, rubber or plastics',
      'Raw fibrous textile materials and substitutes therefor',
      'Tents and tarpaulins',
      'Nets',
      'Sails',
      'Sacks for the transport and storage of materials in bulk',
      'Awnings of textile or synthetic materials',
    ],
  },
  {
    value: '23',
    label: '23',
    type: 'option',
    info: ['Yarns and threads, for textile use'],
  },
  {
    value: '24',
    label: '24',
    type: 'option',
    info: [
      'Textiles and substitutes for textiles',
      'Household linen',
      'Curtains of textile or plastic',
    ],
  },
  {
    value: '25',
    label: '25',
    type: 'option',
    info: ['Clothing, footwear, headgear'],
  },
  {
    value: '26',
    label: '26',
    type: 'option',
    info: [
      'Lace and embroidery, ribbons and braid',
      'Buttons, hooks and eyes, pins and needles',
      'Artificial flowers',
      'Hair decorations',
      'False hair',
    ],
  },
  {
    value: '27',
    label: '27',
    type: 'option',
    info: [
      'Carpets, rugs, mats and matting, linoleum and other materials for covering existing floors',
      'Wall hangings [non-textile]',
    ],
  },
  {
    value: '28',
    label: '28',
    type: 'option',
    info: [
      'Games, toys and playthings',
      'Gymnastic and sporting articles',
      'Decorations for christmas trees',
      'Video game apparatus',
    ],
  },
  {
    value: '29',
    label: '29',
    type: 'option',
    info: [
      'Meat, fish, poultry and game',
      'Meat extracts',
      'Preserved, frozen, dried and cooked fruits and vegetables',
      'Jellies, jams, compotes',
      'Eggs',
      'Milk and milk products',
      'Edible oils and fats',
    ],
  },
  {
    value: '30',
    label: '30',
    type: 'option',
    info: [
      'Coffee, tea, cocoa and artificial coffee',
      'Rice',
      'Tapioca and sago',
      'Flour and preparations made from cereals',
      'Bread, pastries and confectionery',
      'Edible ices',
      'Sugar, honey, treacle',
      'Yeast, baking-powder',
      'Salt',
      'Mustard',
      'Vinegar, sauces [condiments]',
      'Spices',
      'Ice',
    ],
  },
]

export const servicesOptions = [
  {
    value: '31',
    label: '31',
    type: 'option',
    info: [
      'Raw and unprocessed agricultural, aquacultural, horticultural and forestry products',
      'Live animals',
      'Fresh fruits and vegetables, fresh herbs',
      'Natural plants and flowers',
      'Foodstuffs and beverages for animals',
      'Malt',
      'Raw and unprocessed grains and seeds',
      'Bulbs, seedlings and seeds for planting',
    ],
  },
  {
    value: '32',
    label: '32',
    type: 'option',
    info: [
      'Beers',
      'Mineral and aerated waters and other non-alcoholic beverages',
      'Fruit beverages and fruit juices',
      'Syrups and other preparations for making beverages',
    ],
  },
  {
    value: '33',
    label: '33',
    type: 'option',
    info: ['Alcoholic beverages [except beers]'],
  },
  {
    value: '34',
    label: '34',
    type: 'option',
    info: ['Tobacco', "Smokers' articles", 'Matches'],
  },
  {
    value: '35',
    label: '35',
    type: 'option',
    info: [
      'Advertising',
      'Business management',
      'Business administration',
      'Office functions',
    ],
  },
  {
    value: '36',
    label: '36',
    type: 'option',
    info: [
      'Insurance',
      'Financial affairs',
      'Monetary affairs',
      'Real estate affairs',
    ],
  },
  {
    value: '37',
    label: '37',
    type: 'option',
    info: ['Building construction', 'Repair', 'Installation services'],
  },
  {
    value: '38',
    label: '38',
    type: 'option',
    info: ['Telecommunications'],
  },
  {
    value: '39',
    label: '39',
    type: 'option',
    info: ['Transport', 'Packaging and storage of goods', 'Travel arrangement'],
  },
  {
    value: '40',
    label: '40',
    type: 'option',
    info: ['Treatment of materials'],
  },
  {
    value: '41',
    label: '41',
    type: 'option',
    info: [
      'Education',
      'Providing of training',
      'Entertainment',
      'Sporting and cultural activities',
    ],
  },
  {
    value: '42',
    label: '42',
    type: 'option',
    info: [
      'Scientific and technological services and research and design relating thereto',
      'Industrial analysis and research services',
      'Design and development of computer hardware and software',
    ],
  },
  {
    value: '43',
    label: '43',
    type: 'option',
    info: ['Services for providing food and drink', 'Temporary accommodation'],
  },
  {
    value: '44',
    label: '44',
    type: 'option',
    info: [
      'Medical services',
      'Veterinary services',
      'Hygienic and beauty care for human beings or animals',
      'Agriculture, horticulture and forestry services',
    ],
  },
  {
    value: '45',
    label: '45',
    type: 'option',
    info: [
      'Legal services',
      'Security services for the physical protection of tangible property and individuals',
      'Personal and social services rendered by others to meet the needs of individuals',
    ],
  },
]

// export let bigOptions = []

// for (let i = 0; i < 10000; i++) {
//   bigOptions = bigOptions.concat(colourOptions)
// }

export const groupedOptions = [
  {
    label: 'Goods',
    options: goodsOptions,
  },
  {
    label: 'Services',
    options: servicesOptions,
  },
]
